# Generated by Django 5.2 on 2025-05-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('relato', models.TextField()),
                ('status', models.CharField(choices=[('Resolvido', 'Resolvido'), ('Em andamento', 'Em andamento')], default='Em andamento', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
