# Generated by Django 5.2 on 2025-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuariosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agente', 'Agente'), ('usuario', 'Usuário Comum')], default='usuario', max_length=10),
        ),
    ]
