# Generated by Django 5.2 on 2025-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuariosistema_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
